mule:
  env: "local"
  app:
    intercom: "intercom"
    
http:
  host: "0.0.0.0"
  port: "8082"
  private:
    host: "0.0.0.0"
    port: "8091"
https:
  host: "0.0.0.0"
  port: "8443"
  private:
    host: "0.0.0.0"
    port: "8092"
    
anypoint:
  platform:
    config:
      analytics:
        enabled: "true"
